// Generated by CoffeeScript 1.6.3
var app, express, path;

express = require('express');

path = require('path');

app = express();

app.use(express.bodyParser());

app.use(express.methodOverride());

app.use(app.router);

app.use(function(err, req, res, next) {
  console.error(err.stack);
  return res.send(500, "Something broke!");
});
