// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular'], function(angular) {
    'use strict';
    return angular.module('controllers', []);
  });

}).call(this);

/*
//@ sourceMappingURL=controllers.map
*/
