// Generated by CoffeeScript 1.6.3
define([
  'controllers/controllers', function(controllers) {
    return controllers.controller('mainController', [
      '$scope', function($scope) {
        return $scope.name = 'This controller name is: mainController';
      }
    ]);
  }
]);
