// Generated by CoffeeScript 1.6.3
define(['controllers/controllers'], function(controllers) {
  return controllers.controller('RootController', [
    '$scope', function($scope) {
      return $scope.greating = {
        text: 'AiR set by RootController'
      };
    }
  ]);
});
