// Generated by CoffeeScript 1.6.3
define(['angular', 'angularResource', 'controllers/controllers', 'services/services', 'filters/filters', 'directives/directives'], function(angular) {
  return angular.module('AiR', ['ngResource', 'controllers', 'services', 'filters', 'directives']);
});
