// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular', 'angularResource', 'angularRoute', 'controllers/controllers', 'services/services', 'filters/filters', 'directives/directives'], function(angular) {
    return angular.module('AiR', ['ngResource', 'ngRoute', 'controllers', 'services', 'filters', 'directives']);
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
