// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular', 'domReady', 'app'], function(angular, domReady) {
    return domReady(function() {
      return angular.bootstrap(document, ['AiR']);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=bootstrap.map
*/
